# what is the gole of the workflow
# Whenever someone changes the python code
# the linter will check the syntax, format, indentation (linting) is correct or not

name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    steps:
       # this step will automatically clone the code of current branch into the runner
      - name: clone/checkout the code
        uses: actions/checkout@v7

      # setup python/install python
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      # this step will install linter
      - name: install linter
        run: pip install ruff
        
      # this step will run the linter
      - name: check the files for linting
        run: ruff check .
